### ISSUE TITLE
Causes puppet runs on un-supported operating systems to fail

### ISSUE THREAD

**Issue by bhechinger** [joshuabaird/puppet-ipaclient#10]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: sammy: This module does not support operatingsystem FreeBSD at /etc/puppetlabs/puppet/modules/ipaclient/manifests/params.pp:34 on node sammy.4amlunch.net

Can you make it so that an unsupported operating system is just a warning or perhaps ignored? I've got ipaclient in my default group and I really didn't want to have to break it out into linux/freebsd/other/etc at this point yet.

**Comment by stbenjam** [comment]
Does ipa work on FreeBSD? I don't see any mention of it in ports.
