### ISSUE TITLE
sssd.conf issues

### ISSUE THREAD

**Issue by sanderwolf** [joshuabaird/puppet-ipaclient#12]
line 129 in sudoers.pp will break autofs if it's installed as part of this because it explicitly leaves it off of the services line. Needs to be some sort of a check to see if the boolean for autofs is set to true and then set the services line in sssd.conf accordingly.

**Comment by stbenjam** [comment]
Is ipa-client-install setting `autofs` during installation (haven't used automount much personally) or is this something that was pre-existing?  

I've got a fix if it was pre-existing, so I'm not hardcoding the sssd services.

**Comment by stbenjam** [comment]
If it's the pre-existing case, just pushed the changes, stbenjam-ipaclient 2.3.2 should fix it.  If that doesn't fix the problem, let me know and I'll look more into it.

**Comment by sanderwolf** [comment]
I think when the automount.pp runs "/usr/sbin/ipa-client-automount" it's adding the autofs to the services line in sssd.conf. Then when the sudoers.pp runs it's explicitly setting the services line w/o autofs.

**Comment by stbenjam** [comment]
Should be fixed in ada9a73, let me know if that solves your problem!
