### ISSUE TITLE
NTP calling by ipa-client-install is not smart

### ISSUE THREAD

**Issue by bhechinger** [joshuabaird/puppet-ipaclient#14]
ipa-client-install (at least on Ubuntu, not sure if this happens on RHEL/etc) appears to be not smart and attempts to run ntpdate even though ntpd may already be running.

Is there any chance you can stop the ntpd service before running the install script?

**Comment by stbenjam** [comment]
This probably belongs as a bug against FreeIPA itself, I think it runs ntpdate regardless of ntpd status on RHEL too.
