### ISSUE TITLE
ssh_hash_known_hosts under [ssh] section on sssd.conf

### ISSUE THREAD

**Issue by lkthomas** [joshuabaird/puppet-ipaclient#17]
Hi,
1. can you please help to add ssh_hash_known_hosts option which shall be add under [ssh] section on file sssd.conf? default that option is enable and causing host name auto completion on ssh client stop working.
2. Is that possible to add flexibility to add options for example, ipa_ssh_option => [ "ssh_hash_known_hosts false",] to add additional options under each section such as pam, nss...etc? this will make our life easier :)

**Comment by lkthomas** [comment]
any update on this?

**Comment by stbenjam** [comment]
Yea, I could maybe add this, any other sssd settings that would be useful to tweak?

**Comment by lkthomas** [comment]
Hi, Currently I don't see any other settings could tune.

Perhaps you could include extra parameters section so that I could include
anything not exists in the future?

On 28 October 2014 01:26, Stephen Benjamin notifications@github.com wrote:

> Yea, I could maybe add this, any other sssd settings that would be useful
> to tweak?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stbenjam/puppet-ipaclient/issues/17#issuecomment-60632763
> .

## 

Thomas G Lau
Tel: +852-9323-9670

**Comment by joshuabaird** [comment]
@lkthomas I was thinking about this, and I am starting to think that sssd settings should be managed by another module (sssd), and not ipaclient.  I'm in the same boat, but I think I will either move the 'sssd' configuration pieces out to a separate module, or just take care of them in my profiles::ipaclient class.

**Comment by lkthomas** [comment]
LOL, because of my urgent need of getting it working, I already wrote a module from scratch which custom made for my environment already after upgrade to puppet4, thanks for your module tho, it did save my life .... for a while, LOL.
