### ISSUE TITLE
Red Hat / CentOS 6.x: libsss_sudo.so is provided by package sssd-common

### ISSUE THREAD

**Issue by mcarcano** [joshuabaird/puppet-ipaclient#19]
Hello Stephen,
I hope to find you well. I'm trying the ipaclient module on CentOS 6.6 clients deploying the configuration via Katello2 + Foreman 1.6 - that is puppet is controlled by Foreman.
When applying the configuration to the client I got this error:

Dec 10 17:11:26 asup101 puppet-agent[5839]: Execution of '/usr/bin/yum -d 0 -e 0 -y list libsss_sudo' returned 1: Plugin "package_upload" can't be imported
Dec 10 17:11:26 asup101 puppet-agent[5839]: Error: No matching Packages to list
Dec 10 17:11:26 asup101 puppet-agent[5839]: (/Stage[main]/Ipaclient::Sudoers/Package[libsss_sudo]/ensure) change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y list libsss_sudo' returned 1: Plugin "package_upload" can't be imported
Dec 10 17:11:26 asup101 puppet-agent[5839]: (/Stage[main]/Ipaclient::Sudoers/Package[libsss_sudo]/ensure) Error: No matching Packages to list

I noticed that the module issue the command "yum -d 0 -e 0 -y list libsss_sudo", but under CentOS 6.6 the package that provides libsss_sudo.so is "sssd-common".

Anyway, the client get actually registered on ipa (although I suppose the sudo part has not been configured) - however maybe you could fix this as this error is caught by Foreman too, and this lead to an "Host with errors" in the dashboard - This is a quite annoying issue, as the dashboard is supposed to give you a quick idea of the health of your hosts.

Let me know if you need other details.

Regards

**Comment by stbenjam** [comment]
@mcarcano Ah, thanks! This was new in 6.6 and 7.0, where all the sudo functionality was moved directly into SSSD.  Will fix when I get a second.

**Comment by stbenjam** [comment]
@mcarcano Fixed, and I've released 2.4.1 to Puppet Forge

https://forge.puppetlabs.com/stbenjam/ipaclient

**Comment by mcarcano** [comment]
thank you Stephen
