### ISSUE TITLE
Cant use 

### ISSUE THREAD

**Issue by rafilkmp3** [joshuabaird/puppet-ipaclient#32]
I use a foreman for manage my puppet ,

i deploy your class and only uncomment 

class { 'ipaclient':
   principal       => "admin",
   password        => "unicorns",
   server          => ["ipa01.pixiedust.com", "ipa02.pixiedust.com"],
   domain          => "pixiedust.com",
   realm           => "PIXEDUST.COM",
   mkhomedir       => false,
   automount       => true,
   ssh             => false,
   fixed_primary   => true,
   automount_location => "home",
}

and a got a error 
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find class ipaclient for v00-vms01-php-testing.fidelize.com.br on node v00-vms01-php-testing.fidelize.com.br

can you help me ?

**Comment by rafilkmp3** [comment]
all this in init.pp , i am begginer and this is what i understando from your code tks in advance

**Comment by stbenjam** [comment]
It sounds like the module isn't installed on the puppet master? You can try

`puppet module install stbenjam-ipaclient`

on the puppetmaster.
