### ISSUE TITLE
The value 'sssd' cannot be converted to Numeric.

### ISSUE THREAD

**Issue by lkthomas** [joshuabaird/puppet-ipaclient#36]
puppet-agent[1533]: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: The value 'sssd' cannot be converted to Numeric. on node

where exactly is this error come from?

**Comment by stbenjam** [comment]
@lkthomas Just to save you some trouble, I'm not actively maintaining this. Just don't have the time.

**Comment by lkthomas** [comment]
mind to give me some hints to search? I could help a bit.

**Comment by stbenjam** [comment]
`puppet apply --test --debug` or something would give you more info, but you're using Puppet Enterprise or 4.x, and I really doubt this module is going to work on those without some effort.

**Comment by lkthomas** [comment]
that's what I am trying to do now by porting this module to puppet 4.2.x

**Comment by joshuabaird** [comment]
@lkthomas I'll take a look at this in the next few days.
