### ISSUE TITLE
Publish module to forge

### ISSUE THREAD

**Issue by stbenjam** [joshuabaird/puppet-ipaclient#37]
Hi,

I removed my module from the forge: https://forge.puppetlabs.com/stbenjam/ipaclient

I'd upload a new version to the forge on your account when you're ready.

**Comment by joshuabaird** [comment]
:+1:

**Comment by joshuabaird** [comment]
@stbenjam 2.5.0 released @ http://forge.puppetlabs.com/joshuabaird/ipaclient.  Thanks!

**Comment by stbenjam** [comment]
Thanks! :smile: :tada:
