### ISSUE TITLE
libsss_sudo.so

### ISSUE THREAD

**Issue by jimr6007** [joshuabaird/puppet-ipaclient#46]
https://github.com/joshuabaird/puppet-ipaclient/issues/19

I think this is an issue for RH/Centos 6.5 as well now. It's actually about the version of sssd and sssd-ipa not necessarily the OS release.

I've got two systems, one Centos 6.5 and another 6.7. Both have sssd-ipa.x86_64 1.12.4-47.el6, installed via yum from @base 

This module doesn't work correctly on the 6.5 because it wants libsss_sudo which doesn't exist if you have sssd-ipa.x86_64 1.12.4-47.el6

Also, need to change the task that checks that sssd is running to not require libsss_sudo package.

**Comment by joshuabaird** [comment]
@jimr6007, sorry for the delay in getting back to you.  Are you thinking that we need to determine if libsss_sudo should be installed based on the `$::sssd_version` fact, rather than the `$::operatingsystemrelease`?
